---
version: 2.1

executors:
  debian:
    docker:
    - image: debian:bookworm
  ruby:
    docker:
    - image: circleci/ruby:latest

jobs:
  build:
    executor: debian

    steps:
    - run: apt-get update
    - run: apt-get -y install build-essential git openssh-client dpkg-dev debhelper dh-python pybuild-plugin-pyproject python3-all python3-setuptools
    - checkout
    - run: make -f debian/rules binary
    - run: mkdir -p /root/build
    - run: mv ../*.deb /root/build
    - persist_to_workspace:
        root: /root/build
        paths:
        - .
    - store_artifacts:
        path: /root/build

  package:
    executor: ruby

    steps:
    - attach_workspace:
        at: .
    - run: gem install package_cloud
    - run: mkdir -v -p release
    - run: package_cloud push fosdem/video-team/debian/bookworm build/*deb
    - store_artifacts:
        path: release
    - persist_to_workspace:
        root: .
        paths:
        - release

#  release:
#    executor: github
#
#    steps:
#    - run: apk add fakeroot
#    - attach_workspace:
#        at: .
#    - run: mkdir -v -p release
#    - run: fakeroot tar -czvf release/sproxy-${CIRCLE_TAG}.amd64.tar.gz -C build/amd64 sproxy usb_reset wait_next_second cursor_disable.so
#    - run: cd release && sha256sum sproxy-*.tar.gz *deb > sha256sums.txt
#    - run: > 
#        ghr \
#          -u "${CIRCLE_PROJECT_USERNAME}" \
#          -r "${CIRCLE_PROJECT_REPONAME}" \
#          -c "${CIRCLE_SHA1}" \
#          -delete \
#          "${CIRCLE_TAG}" \
#          ./release/

workflows:
  version: 2
  python-osc:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - package:
        requires:
        - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
